export const RETURN_REQUEST_STATUSES = [
  "RETURN_PENDING",
  "RETURN_APPROVED",
  "ITEM_RECEIVED",
  "RETURN_COMPLETED",
];

export const RETURN_STATUS_TRANSITIONS = {
  RETURN_PENDING: ["RETURN_APPROVED", "RETURN_REJECTED"],

  RETURN_APPROVED: ["ITEM_RECEIVED"],

  ITEM_RECEIVED: ["RETURN_COMPLETED"],

  RETURN_COMPLETED: [],

  RETURN_REJECTED: [],
};