import { ORDER_STATUSES } from "./orderStatus";

export const ORDER_STATUS_TRANSITIONS = {
  [ORDER_STATUSES.PLACED]: [
    ORDER_STATUSES.PROCESSING,
    ORDER_STATUSES.CANCELLED,
  ],

  [ORDER_STATUSES.PROCESSING]: [
    ORDER_STATUSES.SHIPPED,
    ORDER_STATUSES.CANCELLED,
  ],

  [ORDER_STATUSES.SHIPPED]: [ORDER_STATUSES.OUT_FOR_DELIVERY],

  [ORDER_STATUSES.OUT_FOR_DELIVERY]: [ORDER_STATUSES.DELIVERED],

  [ORDER_STATUSES.DELIVERED]: [ORDER_STATUSES.RETURN_REQUESTED],

  [ORDER_STATUSES.RETURN_REQUESTED]: [ORDER_STATUSES.RETURNED],

  [ORDER_STATUSES.CANCELLED]: [],

  [ORDER_STATUSES.RETURNED]: [],
};
