import { ORDER_STATUSES } from "./orderStatus";

export const ORDER_TRACKING_STEPS = [
  ORDER_STATUSES.PLACED,
  ORDER_STATUSES.PROCESSING,
  ORDER_STATUSES.SHIPPED,
  ORDER_STATUSES.OUT_FOR_DELIVERY,
  ORDER_STATUSES.DELIVERED,
];
