export const ORDER_STATUSES = {
  PENDING: "PENDING",

  PLACED: "PLACED",

  PROCESSING: "PROCESSING",

  SHIPPED: "SHIPPED",

  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",

  DELIVERED: "DELIVERED",

  CANCELLED: "CANCELLED",
};

export const ITEM_STATUSES = {
  PLACED: "PLACED",

  PROCESSING: "PROCESSING",

  SHIPPED: "SHIPPED",

  DELIVERED: "DELIVERED",

  CANCELLED: "CANCELLED",

  RETURN_PENDING: "RETURN_PENDING",

  RETURN_APPROVED: "RETURN_APPROVED",

  RETURN_REJECTED: "RETURN_REJECTED",

  ITEM_RECEIVED: "ITEM_RECEIVED",

  RETURN_COMPLETED: "RETURN_COMPLETED",
};
