export const ITEM_STATUS_TRANSITIONS = {
  PLACED: ["PROCESSING", "CANCELLED"],

  PROCESSING: ["SHIPPED", "CANCELLED"],

  SHIPPED: ["OUT_FOR_DELIVERY"],

  OUT_FOR_DELIVERY: ["DELIVERED"],

  DELIVERED: [],

  CANCELLED: [],
};
